package com.enterprise.demoapp.api;

import com.enterprise.demoapp.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/** JDBC plumbing shared by the API classes. */
final class Sql {

    // Static helpers only
    private Sql() {
    }

    /** Work on one connection. */
    @FunctionalInterface
    interface Work<T> {
        // Like a Function, but allowed to throw SQLException
        T apply(Connection connection) throws SQLException;
    }

    /** Runs {@code work} on a fresh connection; SQL errors become 500s. */
    static <T> T run(Database database, Work<T> work) {
        // The connection is always closed, also when work throws
        try (Connection c = database.connect()) {
            return work.apply(c);
        } catch (SQLException e) {
            // Unexpected database error: the router turns IllegalStateException into a 500
            throw new IllegalStateException("Database error: " + e.getMessage(), e);
        }
    }

    /** Runs {@code work} in one transaction: all of it is committed, or none of it. */
    static <T> T transaction(Database database, Work<T> work) {
        try (Connection c = database.connect()) {
            // Group all statements into one transaction
            c.setAutoCommit(false);
            try {
                T result = work.apply(c);
                c.commit();
                return result;
            } catch (SQLException | RuntimeException e) {
                // Any failure (including ApiException, e.g. insufficient stock) undoes everything
                c.rollback();
                throw e;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Database error: " + e.getMessage(), e);
        }
    }

    /** The id generated by an INSERT that was prepared with {@code RETURN_GENERATED_KEYS}. */
    static long generatedId(PreparedStatement ps) throws SQLException {
        try (ResultSet keys = ps.getGeneratedKeys()) {
            keys.next();
            return keys.getLong(1);
        }
    }

    /** Runs a {@code SELECT COUNT(*) ... WHERE x = ?} query with one id parameter. */
    static long count(Connection c, String sql, long id) throws SQLException {
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setLong(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getLong(1);
            }
        }
    }
}
